### ISSUE TITLE
Build for Linux x86_64

### ISSUE THREAD

**Issue by lbovet** [TheTechnobear/Mi4Pd#10]
Is it buildable under Linux x86 64bits?
I get:
```
/Mi4Pd/mi/stmlib/dsp/dsp.h:133: Error: no such instruction: `ssat %r14d,$16,%r12d'
```
```
18:17 $ lsb_release -a
LSB Version:	core-9.20170808ubuntu1-noarch:printing-9.20170808ubuntu1-noarch:security-9.20170808ubuntu1-noarch
Distributor ID:	Ubuntu
Description:	Ubuntu 18.04.5 LTS
Release:	18.04
Codename:	bionic
18:20 $ uname -a 
Linux little 4.15.0-128-generic #131-Ubuntu SMP Wed Dec 9 06:57:35 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux
```

**Comment by TheTechnobear** [comment]
not at the moment, you need to add the CXX FLAG -DTEST.

I've noticed I accidentally removed it for apple too :(

Im in the processing of updating all my projects to support Apple Silicone, when I do this I'll chuck in support for linux x86 builds.

**Comment by lbovet** [comment]
Thanks. Looks like we also have to set the -fPIC flag.
It compiles now. I will be able to test it as soon as I get Orac running on my Linux system. Weirdly, the pd orac client works (MEC is working) and I can see the empty modules but the file directory is blank when I try to choose another module. If I get stuck further, I'll open an issue in Orac.
When things work, I'll give a return on experience. My plan is a kind of live guitar loop station with drum machine and synth.

**Comment by TheTechnobear** [comment]
it should be pretty much the same settings as linux arm , but without the arch flags.
and as i mentioned -DTEST which disables the arm (neon) specifics in the MI code.

but i need to reorganise a few things in this area anyway, due to apple silicon...since it also falls foul of the apple=intel  linux=arm.

as for orac, I should point out, I do not want to start specifically support desktop os (windows, linux or mac), I compile them for mac simply to allow for development - but I don't really see it as particularly useful for desktop - given there are so many other choices on desktop... of course, it should work, but I wouldnt want to start adding the binaries as i have to things like rPI etc.

**Comment by lbovet** [comment]
Great, I managed to get the whole Orac/MEC work on my Linux 64. Agreed, there is no point in using it on a desktop but, like you, I want to test my routing and modules without a dev loop involving the target device. And I have no mac....
And also, I may use a spare x86_64 headless mini-computer I have in my drawer I could use instead of buying a rPi. My goal is a quite portable setup with just the mini-computer, a controller (Akai Mini MKII) a midi pedal and a mike.
I could prepare an inuntrisive PR for Orac under a linux-x86_64/ folder with a short guide and also a temporary PR for Mi4Pd (one line for the flags). Otherwise, I will publish some scripts on my own repo.
