### ISSUE TITLE
Potential issue with `lmnts~`

### ISSUE THREAD

**Issue by ryansprott** [TheTechnobear/Mi4Pd#20]
Hello, first of all, thank you very much for all of your hard work porting these fantastic instruments to PD.

While experimenting with the `lmnts~` external I encountered what I believed at the time to be an error.  The `strike_*` and `blow_*` parameters did not seem to affect the audio output of the external.  This led me to [the PD forum](https://forum.pdpatchrepo.info/topic/13439/thetechnobear-s-mi4pd-mutable-instruments-modules-with-updated-helpfiles) where it appeared another user had the same issue.  

This post led me to a [bit of commented code](https://github.com/TheTechnobear/Mi4Pd/blob/master/lmnts/lmnts~.cpp#L163-L172) that I believed to be responsible.  For reference, [this](https://github.com/pichenettes/eurorack/blob/master/elements/elements.cc#L91-L101) is the equivalent code from the Mutable Instruments repo.

Embarrassingly, I have not been able to reproduce this issue since, but I was able to compile a new version with the changes made in [this PR](https://github.com/TheTechnobear/Mi4Pd/pull/18).  However, I cannot tell if these changes made any difference to the external's output.

All this is to ask: do you think it would be worthwhile to reopen the PR?

**Comment by TheTechnobear** [comment]
glad your enjoying it :) 

the strike and blow parameters do affect the audio output... Ive been using this on the organelle for quite a while.
(the reason I originally wrote these externals) 

if you look at lines 159 - 162, you can see they assign blow_in_level, strike_in_level, and gain (to 1.0) ,
which are used in lines 167, 173

the commented out code, looks for "noise" on the inputs, and reduces the input level if its present.
(where noise means, we have a quiet signal) 

this is not relevant in a software only environment, since the input is 'pure', and I would filter any hardware input noise (e.g. from a microphone) elsewhere in my pd patch... since it may well be going to other effects, or recording buffers etc.

so I do not think it's a problem.

sure, we could uncomment the code, and set kNoiseGateThreshold to 0, but thats just wasting cpu cycles ;) 

----

that said... 
I wrote this code many years ago... long before I had eurorack modules, and long before things like vcvrack.
so I wrote this code, without having ever used any of the MI modules... my only experience of these modules was a few youtube videos ;) 
really, it was all written, just by reading the MI code, and figuring out what appear to be going on.
SO.. there could be some small issues... possibly around parameters scaling.

if I was going to review this again, probably what Id do is review it against the VCV rack code, as thats had more usage, and so testing.

however, vcvrack takes a different approach, so may not be entirely valid....
the issue is this MI code is designed to run at 32k sample (iirc).
vcvrack handles this by doing down/upsampling from the native SR.
this is the 'correct' approach - since the MI module code contains a lot of assumptions about a fixed sample.

However, I do not want to do this, since on the hardware Im running on (rPI/Organelle etc) thats quite an overhead, so I kind go just 'hack' my way around it.

BUT i recognise, for a desktop units, this cpu overhead is a non-issue... 
but this is not really designed for desktop pcs... so its a matter of 'focus' really ;)

**Comment by ryansprott** [comment]
Aha, that makes sense.  Thank you!
