### ISSUE TITLE
Compiled versions?

### ISSUE THREAD

**Issue by Jackmattson** [TheTechnobear/Mi4Pd#7]
I'd love to use the externals but don't know how to compile and even took Xcode off my system to save needed space. Is there a Mac compiled version of the group anywhere?

**Comment by TheTechnobear** [comment]
sorry, I dont supply binary versions of this... 

what said, I do compile versions for Orac :) 
which you can find here:

https://github.com/TheTechnobear/Orac/tree/master/macOS/orac/externals

note: this is project is not really well suited to general use on MacOS/Windows since it assumes the sample rate. this is because the underlying MI code assumes this.
to do different sample rates I would need to up/downsample - but I dont really need this for the main purpose of this project which is for things like rPI/organelle etc.
